set_mode:
  target:
    entity:
      integration: yeelight
      domain: light
  fields:
    mode:
      required: true
      selector:
        select:
          options:
            - "color_flow"
            - "hsv"
            - "last"
            - "moonlight"
            - "normal"
            - "rgb"
          translation_key: mode
adjust_bright:
  name: Adjust brightness
  description: Change the brightness by specified percentage within specified duration. If the light is off, it will be turned on.
  target:
    entity:
      integration: yeelight
      domain: light
  fields:
    brightness_step_pct:
      name: Brightness step
      required: true
      description: Change brightness by a percentage.
      selector:
        number:
          min: -100
          max: 100
          unit_of_measurement: "%"
    duration:
      name: Duration
      required: true
      description: Duration it takes to get to next state.
      example: 500
      default: 500
      selector:
        number:
          min: 50
          max: 60000
          unit_of_measurement: "ms"
set_color_scene:
  target:
    entity:
      integration: yeelight
      domain: light
  fields:
    rgb_color:
      example: "[255, 100, 100]"
      selector:
        color_rgb:
    brightness:
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: "%"
set_hsv_scene:
  target:
    entity:
      integration: yeelight
      domain: light
  fields:
    hs_color:
      example: "[300, 70]"
      selector:
        object:
    brightness:
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: "%"
set_color_temp_scene:
  target:
    entity:
      integration: yeelight
      domain: light
  fields:
    kelvin:
      selector:
        number:
          min: 1700
          max: 6500
          step: 100
          unit_of_measurement: K
    brightness:
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: "%"
set_color_flow_scene:
  target:
    entity:
      integration: yeelight
      domain: light
  fields:
    count:
      default: 0
      selector:
        number:
          min: 0
          max: 100
    action:
      default: "recover"
      selector:
        select:
          options:
            - "off"
            - "recover"
            - "stay"
          translation_key: action
    transitions:
      example:
        '[{ "TemperatureTransition": [1900, 1000, 80] }, { "TemperatureTransition":
        [1900, 1000, 10] }]'
      selector:
        object:
set_auto_delay_off_scene:
  target:
    entity:
      integration: yeelight
      domain: light
  fields:
    minutes:
      selector:
        number:
          min: 1
          max: 60
          unit_of_measurement: minutes
    brightness:
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: "%"
set_nightlight_scene:
  name: Nightlight with specific brightness
  description: Turns the nightlight on to the specified brightness. If light is off, it will be turned on.
  target:
    entity:
      integration: yeelight
      domain: light
  fields:
    brightness:
      name: Brightness
      description: The brightness value to set.
      required: True
      selector:
        number:
          min: 1
          max: 100
          unit_of_measurement: "%"
start_flow:
  target:
    entity:
      integration: yeelight
      domain: light
  fields:
    count:
      default: 0
      selector:
        number:
          min: 0
          max: 100
    action:
      default: "recover"
      selector:
        select:
          options:
            - "off"
            - "recover"
            - "stay"
          translation_key: action
    transitions:
      example:
        '[{ "TemperatureTransition": [1900, 1000, 80] }, { "TemperatureTransition":
        [1900, 1000, 10] }]'
      selector:
        object:
set_music_mode:
  target:
    entity:
      integration: yeelight
      domain: light
  fields:
    music_mode:
      required: true
      selector:
        boolean:
